const PDFDocument = require('pdfkit');

const generateCustomerBillPdf = ({ customerSummary, month }) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  doc.fontSize(20).text('Digital Milk Book', { align: 'center' });
  doc.moveDown(0.25);
  doc.fontSize(12).text('Monthly Customer Bill', { align: 'center' });

  doc.moveDown(1.5);
  doc.fontSize(12).text(`Customer: ${customerSummary.customerName}`);
  doc.text(`Phone: ${customerSummary.phone}`);
  doc.text(`Address: ${customerSummary.address}`);
  doc.text(`Billing Month: ${month}`);
  doc.moveDown(1);

  doc.fontSize(14).text('Summary');
  doc.moveDown(0.5);

  const rows = [
    ['Price per Litre', customerSummary.pricePerLitre.toFixed(2)],
    ['Total Litres', customerSummary.totalLitres.toFixed(2)],
    ['Delivery Days', String(customerSummary.deliveryDays)],
    ['Non-Delivery Days', String(customerSummary.nonDeliveryDays)],
    ['Total Amount', customerSummary.totalAmount.toFixed(2)],
  ];

  rows.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').text(`${label}:`, { continued: true });
    doc.font('Helvetica').text(` ${value}`);
    doc.moveDown(0.2);
  });

  doc.moveDown(2);
  doc.fontSize(10).fillColor('gray').text('Generated by Digital Milk Book', { align: 'center' });
  doc.end();

  return doc;
};

module.exports = { generateCustomerBillPdf };
